import { KnowledgeItem, Lesson, Unit } from "@/types/curriculum";

export const grade3KnowledgeItems: KnowledgeItem[] = [
  {
    id: "vocab_hello",
    type: "vocabulary",
    primaryText: "Hello",
    vietnameseMeaning: "Xin chào",
    phoneticIpa: "/həˈloʊ/",
    audioKey: "vocabulary.g3.hello",
    exampleSentence: "Hello! My name is Chú Lười.",
    targetStage: "recognize",
    tags: ["greeting", "beginner"],
  },
  {
    id: "vocab_name",
    type: "vocabulary",
    primaryText: "Name",
    vietnameseMeaning: "Tên",
    phoneticIpa: "/neɪm/",
    audioKey: "vocabulary.g3.name",
    exampleSentence: "What is your name?",
    targetStage: "recall",
    tags: ["identity", "beginner"],
  },
  {
    id: "vocab_friend",
    type: "vocabulary",
    primaryText: "Friend",
    vietnameseMeaning: "Bạn bè",
    phoneticIpa: "/frend/",
    audioKey: "vocabulary.g3.friend",
    exampleSentence: "You are my best friend.",
    targetStage: "understand",
    tags: ["people", "beginner"],
  },
  {
    id: "chunk_whats_your_name",
    type: "chunk",
    primaryText: "What's your name?",
    vietnameseMeaning: "Bạn tên là gì?",
    phoneticIpa: "/wʌts jɔːr neɪm/",
    audioKey: "sentences.g3.whats_your_name",
    exampleSentence: "Hello! What's your name?",
    targetStage: "use",
    tags: ["question", "conversation"],
  },
  {
    id: "chunk_my_name_is",
    type: "chunk",
    primaryText: "My name is ___.",
    vietnameseMeaning: "Tên của mình là ___.",
    phoneticIpa: "/maɪ neɪm ɪz/",
    audioKey: "sentences.g3.my_name_is",
    exampleSentence: "My name is Nam.",
    targetStage: "produce",
    tags: ["introduction", "conversation"],
  },
  {
    id: "chunk_nice_to_meet_you",
    type: "chunk",
    primaryText: "Nice to meet you.",
    vietnameseMeaning: "Rất vui được gặp bạn.",
    phoneticIpa: "/naɪs tuː miːt juː/",
    audioKey: "sentences.g3.nice_to_meet_you",
    exampleSentence: "Nice to meet you, Chú Lười!",
    targetStage: "transfer",
    tags: ["politeness", "conversation"],
  },
];

export const sampleLesson1: Lesson = {
  id: "lesson_g3_u1_l1",
  unitId: "unit_g3_u1",
  order: 1,
  title: "What's your name?",
  titleVi: "Bạn tên là gì?",
  description: "Làm quen và tự tin giới thiệu tên cùng Chú Lười.",
  knowledgeItems: grade3KnowledgeItems,
  activities: [
    {
      id: "act_1_listen_repeat",
      type: "listen_and_repeat",
      prompt: "Listen and repeat the word 'Hello'",
      instructionVi: "Lắng nghe và phát âm theo Chú Lười nhé!",
      knowledgeItemIds: ["vocab_hello"],
      audioKey: "vocabulary.g3.hello",
      targetExpectedText: "Hello",
      rewardPoints: { stars: 1, xp: 10, petFood: 1 },
    },
    {
      id: "act_2_word_match",
      type: "word_match",
      prompt: "Match 'Friend' with its Vietnamese meaning",
      instructionVi: "Chọn nghĩa tiếng Việt chính xác của từ 'Friend'.",
      knowledgeItemIds: ["vocab_friend"],
      options: [
        { id: "opt_1", label: "Bạn bè", isCorrect: true },
        { id: "opt_2", label: "Gia đình", isCorrect: false },
        { id: "opt_3", label: "Thầy cô", isCorrect: false },
      ],
      rewardPoints: { stars: 1, xp: 10, petFood: 0 },
    },
    {
      id: "act_3_choose_correct",
      type: "choose_correct",
      prompt: "How do you ask someone's name in English?",
      instructionVi: "Câu nào dùng để hỏi tên bạn?",
      knowledgeItemIds: ["chunk_whats_your_name"],
      options: [
        { id: "opt_a", label: "What's your name?", isCorrect: true },
        { id: "opt_b", label: "How are you?", isCorrect: false },
        { id: "opt_c", label: "Goodbye!", isCorrect: false },
      ],
      rewardPoints: { stars: 1, xp: 15, petFood: 1 },
    },
    {
      id: "act_4_fill_chunk",
      type: "fill_in_chunk",
      prompt: "Complete the sentence: 'My ___ is Linh.'",
      instructionVi: "Điền từ còn thiếu vào chỗ trống.",
      knowledgeItemIds: ["vocab_name", "chunk_my_name_is"],
      options: [
        { id: "opt_name", label: "name", isCorrect: true },
        { id: "opt_hello", label: "hello", isCorrect: false },
        { id: "opt_friend", label: "friend", isCorrect: false },
      ],
      rewardPoints: { stars: 1, xp: 15, petFood: 1 },
    },
    {
      id: "act_5_speak_aloud",
      type: "speak_aloud",
      prompt: "Say: 'Nice to meet you.'",
      instructionVi: "Nhấn giữ micro và nói câu 'Nice to meet you.'",
      knowledgeItemIds: ["chunk_nice_to_meet_you"],
      targetExpectedText: "Nice to meet you",
      rewardPoints: { stars: 2, xp: 20, petFood: 1 },
    },
    {
      id: "act_6_mini_conversation",
      type: "mini_conversation",
      prompt: "Chú Lười asks: 'Hello! What's your name?' — How do you reply?",
      instructionVi: "Chú Lười đang hỏi tên bạn đấy! Hãy trả lời thật to nhé!",
      knowledgeItemIds: ["chunk_whats_your_name", "chunk_my_name_is"],
      targetExpectedText: "My name is Chú Lười's Friend",
      hint: "Bắt đầu bằng: 'My name is...'",
      rewardPoints: { stars: 3, xp: 30, petFood: 2 },
    },
  ],
};

export const sampleUnit1: Unit = {
  id: "unit_g3_u1",
  grade: 3,
  semester: 1,
  order: 1,
  topicName: "Hello & Friends",
  topicNameVi: "Xin Chào & Những Người Bạn",
  description: "Học cách chào hỏi, hỏi tên và kết bạn mới bằng tiếng Anh.",
  lessons: [sampleLesson1],
};
